let urlPrefix = "https://media.giphy.com/media/";

weather = [
  {
    weather: "heavy intensity rain",
    currentTemp: "",
    gifDescription: "Al Roker in rain",
    src: urlPrefix + "xUPGcdhiQf2vbfDCyk/giphy.gif",
  },
  {
    weather: "moderate rain",
    currentTemp: "",
    gifDescription: "Al Roker in rain",
    src: urlPrefix + "xUPGcdhiQf2vbfDCyk/giphy.gif",
  },
  {
    weather: "rain",
    currentTemp: "",
    gifDescription: "Claymation rain cloud",
    src: urlPrefix + "hk6czgfmwVJS0/giphy.gif",
  },
  {
    weather: "shower rain",
    currentTemp: "",
    gifDescription: "Guy with remote control",
    src: urlPrefix + "l4FGkdtLGfpUiBdFC/giphy.gif",
  },
  {
    weather: "thunderstorm",
    currentTemp: "",
    gifDescription: "Thunderstorm in coffee cup",
    src: urlPrefix + "3oEjIa5lbVSfv8a9s4/giphy.gif",
  },
  {
    weather: "light rain",
    currentTemp: "",
    gifDescription: "Al Roker in light rain",
    src: urlPrefix + "xUPGcILSlV4VjCZ9PG/giphy.gif",
  },
  {
    weather: "drizzle",
    currentTemp: "",
    gifDescription: "Al Roker in light rain",
    src: urlPrefix + "xUPGcILSlV4VjCZ9PG/giphy.gif",
  },
  {
    weather: "light intensity drizzle",
    currentTemp: "",
    gifDescription: "Al Roker in light rain",
    src: urlPrefix + "xUPGcILSlV4VjCZ9PG/giphy.gif",
  },
  {
    weather: "heavy intensity drizzle",
    currentTemp: "",
    gifDescription: "woman in bathing suit, on ground with rain",
    src: urlPrefix + "",
  },
  {
    weather: "clear sky",
    currentTemp: "",
    gifDescription: "cat flying through sky",
    src: urlPrefix + "VxbvpfaTTo3le/giphy.gif",
  },
  {
    weather: "sky is clear",
    currentTemp: "",
    gifDescription: "cat flying through sky",
    src: urlPrefix + "VxbvpfaTTo3le/giphy.gif",
  },
  {
    weather: "",
    currentTemp: "> 90",
    gifDescription: "Kramer turkey",
    src: urlPrefix + "5xqKWd6761tkY/giphy.gif",
  },
  {
    weather: "",
    currentTemp: "< 25",
    gifDescription: "slipping penguin",
    src: urlPrefix + "BvBEozfsXWWHe/giphy.gif",
  },
  {
    weather: "",
    currentTemp: "> 85",
    gifDescription: "melting popcicle",
    src: urlPrefix + "xUA7b0fCaEIjdwJXTa/giphy.gif",
  },
  {
    weather: "snow",
    currentTemp: "",
    gifDescription: "Al Roker in snow",
    src: urlPrefix + "xUPGcChZRE8p2djeiQ/giphy.gif",
  },
  {
    weather: "few clouds",
    currentTemp: "",
    gifDescription: "hanging rocking clouds",
    src: urlPrefix + "h0VzgrFX9AKXK/giphy.gif",
  },
  {
    weather: "clouds",
    currentTemp: "",
    gifDescription: "",
    src: urlPrefix + "rrFcUcN3MFmta/giphy.gif",
  },
  {
    weather: "scattered clouds",
    currentTemp: "",
    gifDescription: "sloth wearing sunglasses reflecting clouds",
    src: urlPrefix + "rrFcUcN3MFmta/giphy.gif",
  },
  {
    weather: "broken clouds",
    currentTemp: "",
    gifDescription: "cloud falls on lady",
    src: urlPrefix + "rrFcUcN3MFmta/giphy.gif",
  },
  {
    weather: "overcast clouds",
    currentTemp: "",
    gifDescription: "black and white moody cloudy sky",
    src: urlPrefix + "lKKXOCVviOAXS/giphy.gif",
  },
  {
    weather: "dust",
    currentTemp: "",
    gifDescription: "dust gif",
    src: urlPrefix + "l4pSWPz4u8zQcXjY4/giphy.gif",
  },
  {
    weather: "light snow",
    currentTemp: "",
    gifDescription: "oscar the grouch",
    src: urlPrefix + "4jGoaiwq9oRri/giphy.gif",
  },
  {
    weather: "mist",
    currentTemp: "",
    gifDescription: "",
    src: urlPrefix + "apB1oxVnxPaLu/giphy.gif",
  },
  {
    weather: "fog",
    currentTemp: "",
    gifDescription: "glass cup on it's side, fog pouring out",
    src: urlPrefix + "apB1oxVnxPaLu/giphy.gif",
  },
  {
    weather: "haze",
    currentTemp: "",
    gifDescription: "cat smoke",
    src: urlPrefix + "HknSLLEbzZCoM/giphy.gif",
  },
  {
    weather: "smoke",
    currentTemp: "",
    gifDescription: "cousin itt smoking",
    src: urlPrefix + "5xtDarLUQd5DqgXHJks/giphy.gif",
  },
  {
    weather: "sleet",
    currentTemp: "",
    gifDescription: "wet cat",
    src: urlPrefix + "26BGD4XaoPO3zTz9K/giphy.gif",
  },
  {
    weather: "shower sleet",
    currentTemp: "",
    gifDescription: "wet cat",
    src: urlPrefix + "26BGD4XaoPO3zTz9K/giphy.gif",
  },
  {
    weather: "rain and snow",
    currentTemp: "",
    gifDescription: "elves with umbrellas",
    src: urlPrefix + "3osBLtpZ8xhRZRYaGs/giphy.gif",
  },
  {
    weather: "light rain and snow",
    currentTemp: "",
    gifDescription: "elves with umbrellas",
    src: urlPrefix + "3osBLtpZ8xhRZRYaGs/giphy.gif",
  },
  {
    weather: "light shower snow",
    currentTemp: "",
    gifDescription: "elves with umbrellas",
    src: urlPrefix + "3osBLtpZ8xhRZRYaGs/giphy.gif",
  },
  {
    weather: "shower snow",
    currentTemp: "",
    gifDescription: "elves with umbrellas",
    src: urlPrefix + "3osBLtpZ8xhRZRYaGs/giphy.gif",
  },
  {
    weather: "heavy shower snow",
    currentTemp: "",
    gifDescription: "spinning slushy. replace this one",
    src: urlPrefix + "l378an2e0zaQWvSZW/giphy.gif",
  },
];
